version: '3.8'

services:
  postgres:
    container_name: nextjs-computer-demo-13-postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      # - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    container_name: nextjs-computer-demo-13-pgadmin4
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    restart: always

  # nextjs:
  #   container_name: nextjs-computer-demo-13-app
  #   image: nextjs-computer-demo-13
  #   build:
  #     # context: .
  #     dockerfile: Dockerfile.test
  #   restart: always
  #   # environment:
  #   #   - PORT=${PORT}
  #   env_file:
  #     - .env
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - ./app:/app
  #     - /app/node_modules
  #     - /app/.next
